### ISSUE TITLE
Problem with opening the BlendGDSII.exe

### ISSUE THREAD

**Issue by Ege5Gurtan** [SwaggerNiels/BlenderGDSII#1]
I followed the following instructions: 

> Installation is very easy!
> On this github page go to the Releases tab.
> Here you can download the zip-file, unpack it, and run the BlendGDSII.exe

However I get the following error when I try to run the executable.
![error](https://github.com/SwaggerNiels/BlenderGDSII/assets/64253009/07436f71-2537-46f9-ae5c-75c60a161bef)

**Comment by SwaggerNiels** [comment]
My program indeed assumes some things.
For instance that you have Blender installed under the path: 
`C:\Program Files\Blender Foundation\Blender*\blender.exe`
(Here `*` is any number of character, in order to match the particular version number of blender you might have installed)

So please install Blender from the website:
https://www.blender.org

If you are using MacOS, then I am not sure, but you would have to let me know. The path will probably be something like:
`Applications/Blender.app/Contents/MacOS/Blender/`

Please let me know if this helped resolve the problem.

**Comment by DeLorrenzo** [comment]
Hi Niels, 
I have the same issue. 
I have seen in the source code for BlenderGDSII that at the line 22 the tool expects to find the Path for Blender. 
On my PC I have to use Blender portable in another place as your tool expects it. I can't use the Blender Installer.
Question : istn't possible to start the tool AND then to be able to set the path for Blender somewhere in the options ?
Thank you & regards

**Comment by SwaggerNiels** [comment]
Hi DeLorrenzo,
Good suggestion indeed.
Since you are the second one to remark this I have added a new version of the program.
Now you can select whatever Blender path you want with a new submenu. 

![afbeelding](https://github.com/SwaggerNiels/BlenderGDSII/assets/58084010/aa39eb74-f4b0-421b-8cc1-74e75d291fab)

This also allows users to change the Blender version with which they want to open the program.
It is still best to open the stl versions of GDSII files in Blender 3.6.
Although version 4.0 will work as well you might have to zoom out before you can see your GDSII design.
