### ISSUE TITLE
button convert and open is not working

### ISSUE THREAD

**Issue by OtisYang** [SwaggerNiels/BlenderGDSII#2]
Hi, 

I tried your BlenderGDSII but it is not working for me. Even with the example, the open in Blender is not working. It could open the Blender but no stl file was loaded. Also, if I select my own gds file, then selecet convert, nothing happens. 

The outcome image from your demonstration looks amazing to me! I hope I can use your software to demonstrate my layout.

Could you please help me?

**Comment by SwaggerNiels** [comment]
He OtisYang,

Thank you for the kind words. There are many possible problems that cause your issue.
It is my own fault for not having made proper error logging.
In any case, the example should work out of the box. So one possibility,(if you are not familiar with Blender itself) is that the viewport is not focused on the models. It depends on the Blender version that you have installed, I have noticed.

If this would be the case, you should still see your layers in the top right of the object tree in Blender. Then you select them there, and press numpad "." While hovering the viewport to focus on the objects.

Another possibility is that you should check the checkboxes in the UI where you also specify the material and height. (blue box before every layer)

Please let me know if this helped you. Otherwise check whether the STL files are generated (should be in the folder of the GDSII you open). If not then we can start there.

I dont know what timezone you live, but we could do a small videocall if you need, im sure I can figure it out in a couple of minutes then if these options dont help.

Let me know!
Good luck.

**Comment by OtisYang** [comment]
Hi!

Thank you so much for your reply and offering! I think I figured out the issue with the converting. My pattern is on the order of 100um and I input the height as 100 nm. In that case, no stl is generated from the convert button. If I increase the value to 5000nm, then it works fine. 

For the loading button with examples, it indeed did not show any objects on the top right corner. But the convert button works cause I can see the files updated in the folder.
![image](https://github.com/user-attachments/assets/68c36c8d-d92f-4837-aff0-3d84080baac9)

So, I believe the example file and my file has the same loading issue related to the Blender version/settings. Maybe you can specify the Blender version you have and I can get the version and try again. 

Thanks!

**Comment by SwaggerNiels** [comment]
Good that you figured it out yourself!
Indeed I have not used my own tool with the new Blender versions yet, but I notice that the height is badly defined.

I have updated the code and will try to push it as soon as possible, to make sure it is correct again.

Also the materials will be updated since EEVEE uses new settings for transparency and whatnot.

Let me know if you need more help, and good luck with your design!
